// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1mP8oUwjn3g4e7sx5sae4NLGn-uKLpy4',
    appId: '1:224159145866:android:a6cd92b8f56c544650b273',
    messagingSenderId: '224159145866',
    projectId: 'social-media-app-c75f9',
    databaseURL: 'https://social-media-app-c75f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'social-media-app-c75f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU6UR_x8YO2BL1_AWpNjR0RyGbT5XcWZ0',
    appId: '1:224159145866:ios:4098f50ee7a16b2450b273',
    messagingSenderId: '224159145866',
    projectId: 'social-media-app-c75f9',
    databaseURL: 'https://social-media-app-c75f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'social-media-app-c75f9.appspot.com',
    iosClientId: '224159145866-h51tp8hdisfpatg0669oi1ie19kf3tvj.apps.googleusercontent.com',
    iosBundleId: 'uz.obidkhandev.payme',
  );
}
